name: Deploy App

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Verwende Secrets
        run: echo "Das Secret ist ${{ secrets.API_KEY }}" 
